### ISSUE TITLE
Remove Search, Rename Explore, and add new Research tab

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#156]
1. Is your feature request related to a problem? Please describe.
Search and Explore tabs in the top menu basically do the same thing, so we’re getting rid of the Search tab, renaming the Explore tab and creating a New Research Tab.

Describe the solution you'd like:
We would like to remove the “Search” tab from the top menu and rename the “Explore” tab “Explore & Search”. 

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

2. Is your feature request related to a problem? Please describe.
We would like a place to put the research coming out about the WPHP, and think the best way to do this is a “Research” tab in the top menu. the Research tab should function like the other blog post sections (ie. About) allowing us to add subpages and for the menu items to appear under "Research."

Describe the solution you'd like:
We would like to add a “Research” tab to the top menu where the “Search” tab currently is (between “Explore” and “Spotlight”).

**Comment by joeytakeda** [comment]
@mnl101 : Thanks for filing this. One question from a design standpoint: I think one of the benefits of removing the Search from the navigation was to make room for the "Research" tab; renaming "Explore" to "Explore & Search" doesn't really give us any more real estate in the navigation to work with.

A couple ideas:

* Rename Explore to Discover (or just keep it as Explore)
* Rename News & Events to simply News (since the majority of the blog posts will move over to Research, I assume?)

Thoughts?

**Comment by mnl101** [comment]
Hi Joey,

Yes we can just go to news, that is fine!

Does that mean we keep Explore & Search?

I think that we are concerned that people will not know that explore includes search….

Michelle

**Comment by ubermichael** [comment]
Current suggestion: About, Data, Research, Spotlight, News, Login.

**Comment by ubermichael** [comment]
> we would like to go with the following top menu items: About, Database, Research, Spotlight, News. Database will replace Explore; we would like “Search” added before the drop down items, Titles, Persons, Firms, so they read “Search Titles” “Search Persons” and “Search Firms”.
