### ISSUE TITLE
Person Search: Unable to search for a person by their full name in the “person” search.

### ISSUE THREAD

**Issue by mnl101** [sfu-dhil/wphp#223]
Describe the bug: 
When we search for a full name in the person search, it brings up all results that include the first or last name, and does not bring up the most relevant result first. If you search for the full name in quotations, it produces no results.

To reproduce:
Click on “Database” in the top header and “Person Search” in the drop down menu
Type in Charlotte Smith (no quotations) and hit search.
It brings up all “Charlotte” and all “Smith” (99) results. 
Type in “Charlotte Smith” (with quotations) and hit search
It brings up zero results, even though we have two Charlotte Smiths in the database
Same for Smith, Charlotte (99 results) and "Smith, Charlotte" (0 results)
Charlotte and Smith (100 results); "Charlotte and Smith" (0 results)

Expected results:
When a user searches for a full name, it should bring up the most relevant entry first (ie. the entry that has both names the user searched for).

Additional context: N/A

**Comment by ubermichael** [comment]
The problem here is that the first name and last name fields are different. So when searching for a person by name we must search the first name and last name fields. 

So I have changed the person name search so that including quotes around a name will change the nature of searching from a full text match to a first name last name comparison.

Examples: 
 - `"charlotte smith"` will find the one Charlotte Smith in the database.
 - `charlotte smith` will find all the charlottes and all the smiths
 - `"rachel biggs"` will not find Rachel Charlotte Biggs because the search  term must include Charlotte.
 - `"rachel%biggs"` will find Rachel Charlotte Biggs. % is a wildcard  character for this one specific case.

**Comment by mnl101** [comment]
thanks Michael, good solution!
