### ISSUE TITLE
Unable to reformat the acknowledgements page

### ISSUE THREAD

**Issue by kkatemoffatt** [sfu-dhil/wphp#285]
### What isn’t working as expected on the website?

The acknowledgements page has weird formatting going on, but we're unable to reformat it ourselves

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

<img width="961" alt="acknowledgements bug" src="https://user-images.githubusercontent.com/80983260/142272494-59ae3db2-adc7-44c0-a96d-872a37ebdb4f.png">

### What is the URL of the page where you encountered the bug?

https://womensprinthistoryproject.com/blog/page/2

### What steps did you take before you encountered the bug?

1. Clicked on "About"
2. Clicked on "Acknowledgements"
3. Clicked "Edit"
4. The text looks fine in the editing box, but does not display properly on the page itself

### What browser, operating system, and device were you using when you encountered the error?

Chrome, Windows 10, desktop

**Comment by joeytakeda** [comment]
Hi @kkatemoffatt : This is an interesting situation! I think it's due to the links on the images and how that combines with the explicit left-alignment on the image. The reason that there's a discrepancy between the editor and the public page is because the editor doesn't actually make the links (since you need to be able to click the image when editing without going to that link) and, instead, gives instructions for the database to create a link around the image when the page is rendered. So when the page is shown to the public, it is a slightly modified version of what's in the editor and, in this case, it causes the strange display. 

But I think the fix should be simple: you can remove the left alignment for each image (i.e. click each image and unselect the left-align icon in the toolbar), which should make everything display properly.

**Comment by kkatemoffatt** [comment]
That worked, Joey! Thanks so much!
